"use client";
import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";
import { IsMobileThemeProvider } from "./context/NavBarContext";
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <IsMobileThemeProvider>
          <body className="relative box-border overflow-x-hidden h-full flex flex-col min-h-screen">
            <NavBar />
            <main>{children}</main>

            <Footer />
          </body>
        </IsMobileThemeProvider>
      </Provider>
    </html>
  );
}
